/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Vanessa Estefania Corredor Andrade
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPresentacion = new javax.swing.JPanel();
        textoinfo = new javax.swing.JLabel();
        Reloj = new javax.swing.JLabel();
        tlAgenda = new javax.swing.JLabel();
        lbfondorosa = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Etiqueta1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Etiqueta2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPresentacion.setBackground(new java.awt.Color(240, 104, 104));
        panelPresentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoinfo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        textoinfo.setForeground(new java.awt.Color(255, 255, 255));
        textoinfo.setText("¡Bienvenido a agenda !");
        panelPresentacion.add(textoinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        Reloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/reloj.png"))); // NOI18N
        panelPresentacion.add(Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        tlAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/texto.png"))); // NOI18N
        panelPresentacion.add(tlAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbfondorosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/fondo.png"))); // NOI18N
        panelPresentacion.add(lbfondorosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 500));

        getContentPane().add(panelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, 300, 500));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Etiqueta1.setBackground(new java.awt.Color(237, 247, 152));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-enter-40.png"))); // NOI18N

        javax.swing.GroupLayout Etiqueta1Layout = new javax.swing.GroupLayout(Etiqueta1);
        Etiqueta1.setLayout(Etiqueta1Layout);
        Etiqueta1Layout.setHorizontalGroup(
            Etiqueta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Etiqueta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Etiqueta1Layout.setVerticalGroup(
            Etiqueta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Etiqueta1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Etiqueta2.setBackground(new java.awt.Color(128, 214, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-registration-40.png"))); // NOI18N

        javax.swing.GroupLayout Etiqueta2Layout = new javax.swing.GroupLayout(Etiqueta2);
        Etiqueta2.setLayout(Etiqueta2Layout);
        Etiqueta2Layout.setHorizontalGroup(
            Etiqueta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Etiqueta2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        Etiqueta2Layout.setVerticalGroup(
            Etiqueta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Etiqueta2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(250, 181, 122));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/close.png"))); // NOI18N
        jLabel3.setText("x");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 980, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Etiqueta1;
    private javax.swing.JPanel Etiqueta2;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Reloj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbfondorosa;
    private javax.swing.JPanel panelPresentacion;
    private javax.swing.JLabel textoinfo;
    private javax.swing.JLabel tlAgenda;
    // End of variables declaration//GEN-END:variables
}
