/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Vanessa Estefania Corredor Andrade
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
       setLocationRelativeTo(null);
       //jframe transparente
       setBackground(new Color(0, 255, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        panelPresentacion = new javax.swing.JPanel();
        btnPnSesion = new javax.swing.JButton();
        btnPnRegister = new javax.swing.JButton();
        textoinfo = new javax.swing.JLabel();
        Reloj = new javax.swing.JLabel();
        tlAgenda = new javax.swing.JLabel();
        lbfondorosa = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        PnSlider = new diu.swe.habib.JPanelSlider.JPanelSlider();
        PnInisio = new javax.swing.JPanel();
        PnRegistro = new javax.swing.JPanel();

        jTextField6.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(240, 104, 104));
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(240, 104, 104)));
        jTextField6.setName("TxtUusuario"); // NOI18N
        jTextField6.setOpaque(false);
        jTextField6.setSelectionColor(new java.awt.Color(240, 104, 104));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPresentacion.setBackground(new java.awt.Color(240, 104, 104));
        panelPresentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPnSesion.setBackground(new java.awt.Color(237, 247, 152));
        btnPnSesion.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnPnSesion.setForeground(new java.awt.Color(240, 104, 104));
        btnPnSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-enter-40.png"))); // NOI18N
        btnPnSesion.setText("Iniciar sesion");
        btnPnSesion.setBorder(null);
        btnPnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnSesionActionPerformed(evt);
            }
        });
        panelPresentacion.add(btnPnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, -1));

        btnPnRegister.setBackground(new java.awt.Color(128, 214, 255));
        btnPnRegister.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        btnPnRegister.setForeground(new java.awt.Color(240, 104, 104));
        btnPnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-registration-40.png"))); // NOI18N
        btnPnRegister.setText("Registrate");
        btnPnRegister.setBorder(null);
        btnPnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnRegisterActionPerformed(evt);
            }
        });
        panelPresentacion.add(btnPnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 120, -1));

        textoinfo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        textoinfo.setForeground(new java.awt.Color(255, 255, 255));
        textoinfo.setText("¡Bienvenido a agenda !");
        panelPresentacion.add(textoinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        Reloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/reloj.png"))); // NOI18N
        panelPresentacion.add(Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        tlAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/texto.png"))); // NOI18N
        panelPresentacion.add(tlAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbfondorosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading/fondo.png"))); // NOI18N
        panelPresentacion.add(lbfondorosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, 510));

        getContentPane().add(panelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 10, 300, 490));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(250, 181, 122));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/close.png"))); // NOI18N
        close.setText("x");
        Fondo.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 40, 40));

        PnSlider.setName("PnSlider"); // NOI18N

        PnInisio.setBackground(new java.awt.Color(255, 51, 51));
        PnInisio.setName("PnInisio"); // NOI18N

        javax.swing.GroupLayout PnInisioLayout = new javax.swing.GroupLayout(PnInisio);
        PnInisio.setLayout(PnInisioLayout);
        PnInisioLayout.setHorizontalGroup(
            PnInisioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnInisioLayout.setVerticalGroup(
            PnInisioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PnSlider.add(PnInisio, "card2");

        PnRegistro.setBackground(new java.awt.Color(255, 204, 255));
        PnRegistro.setName("PnRegistro"); // NOI18N

        javax.swing.GroupLayout PnRegistroLayout = new javax.swing.GroupLayout(PnRegistro);
        PnRegistro.setLayout(PnRegistroLayout);
        PnRegistroLayout.setHorizontalGroup(
            PnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnRegistroLayout.setVerticalGroup(
            PnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PnSlider.add(PnRegistro, "card3");

        Fondo.add(PnSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 580, 390));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 1010, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPnRegisterActionPerformed

    private void btnPnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnSesionActionPerformed
    
    }//GEN-LAST:event_btnPnSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public javax.swing.JPanel PnInisio;
    public javax.swing.JPanel PnRegistro;
    public diu.swe.habib.JPanelSlider.JPanelSlider PnSlider;
    private javax.swing.JLabel Reloj;
    public javax.swing.JButton btnPnRegister;
    public javax.swing.JButton btnPnSesion;
    public javax.swing.JLabel close;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbfondorosa;
    private javax.swing.JPanel panelPresentacion;
    private javax.swing.JLabel textoinfo;
    private javax.swing.JLabel tlAgenda;
    // End of variables declaration//GEN-END:variables
}
